# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Neighborhood.delete_all
Place.delete_all

upper_east_side = Neighborhood.create(name: "Upper East Side", latitude: 40.7692, longitude: -73.9656, description: "The Upper East Side is a neighborhood in the borough of Manhattan in New York City, between Central Park and the East River. The Upper East Side lies within an area bounded by 59th Street to 96th Street, and the East River to Fifth Avenue-Central Park.")
upper_west_side = Neighborhood.create(name: "Upper West Side", latitude: 40.790278, longitude: -73.959722, description: "The Upper West Side is a neighborhood in the borough of Manhattan, New York City, that lies between Central Park and the Hudson River and between West 59th Street and West 116th Street. Like the Upper East Side, the Upper West Side is an upscale, primarily residential area with many of its residents working in more commercial areas in Midtown and Lower Manhattan. It has the reputation of being home to New York City's cultural, intellectual hub (with Columbia University located at the north end of the neighborhood), and artistic workers (with Lincoln Center located at the south end), while the Upper East Side is traditionally perceived to be home to commercial and business types.")
midtown_east = Neighborhood.create(name: "Midtown East", latitude: 40.747, longitude: -73.986, description: "Midtown Manhattan, or simply Midtown, is a geographic area of Manhattan, New York City. It is home to some of the city's most iconic buildings, including the Empire State Building, the Chrysler Building, and the United Nations Headquarters. It contains world-famous commercial zones such as Rockefeller Center, Broadway, and Times Square.")
hells_kitchen = Neighborhood.create(name: "Hell's Kitchen", latitude: 40.763186, longitude: -73.994508, description: "Hell's Kitchen, also known as Clinton and Midtown West, is a neighborhood of Manhattan in New York City located between 34th Street in the south, 59th Street in the north, Eighth Avenue in the east and the Hudson River to the west.[1] The area provides transportation, hospital and warehouse infrastructure support to the Midtown Manhattan business district. Its gritty reputation kept real estate prices below those of most other areas of Manhattan until the early 1990s; rents have increased dramatically since and are currently above the Manhattan average")
greenwich_village = Neighborhood.create(name: "Greenwich Village", latitude: 40.733889, longitude: -74.001111, description: "Greenwich Village, often referred to by locals as simply 'the Village', is a largely residential neighborhood on the west side of Lower Manhattan in the city of New York City, in the U.S. state of New York. A large majority of the district is home to upper middle class families. Greenwich Village, however, was known in the late 19th to mid 20th centuries as an artists' haven, the bohemian capital, and the East Coast birthplace of both the Beat and '60s counterculture movements. What provided the initial attractive character of the community eventually contributed to its gentrification and commercialization. The name of the village was Anglicized from the Dutch name Groenwijck, meaning 'Green District', into Greenwich, a borough of London")
east_village = Neighborhood.create(name: "East Village", latitude: 40.7275, longitude: -73.985833, description: "The East Village is a neighborhood in the borough of Manhattan in New York City, lying east of Greenwich Village, south of Gramercy and Stuyvesant Town, and north of the Lower East Side.")
lower_east_side = Neighborhood.create(name: "Lower East Side", latitude: 40.717222, longitude: -73.989722, description: "The Lower East Side, sometimes abbreviated as LES, is a neighborhood in the southeastern part of the New York City borough of Manhattan. It is roughly bounded by the Bowery to the west, East Houston Street to the north, the East River to the east, and Canal Street to the south. The western boundary below Grand Street veers east off of the Bowery to approximately Essex Street")
financial_district = Neighborhood.create(name: "Financial District", latitude: 40.707499, longitude: -74.011153, description: "The Financial District, located in the borough of Manhattan in New York City, is a neighborhood on the southeastern side of Manhattan which comprises the offices and headquarters of many of the city's major financial institutions, including the New York Stock Exchange and the Federal Reserve Bank of New York. The World Trade Center existed in the neighborhood until the September 11 attacks and is currently being rebuilt. The neighborhood roughly overlaps the boundaries of the New Amsterdam settlement in the late 17th century and has a residential population of about 56,000")




grace_mansion = Place.create(name: "Gracie Mansion", address: "East End Ave. at 88th Street", latitude: 40.7761101, longitude: -73.9432478, description: "Grace Mansion is the residence for the New York City Mayor.  The mansion can only be used for city business.  Only visiting public officials or the mayor's family can reside there.  As a result, Rudy Giuliani was unable to live there with his then girlfriend since they were not married.  The mansion is featured in the movie Ghostbusters II when the gang meets with the mayor.", neighborhood_id: upper_east_side.id)
frick = Place.create(name: "Frick Collection", address: "1 East 70th Street, at Fifth Avenue", latitude: 40.771181, longitude: -73.96735, description: "The Frick Collection is a large private collection of the late Henry Clay Frick.  The collection includes paintings by European masters as well as restored furniture.  Fun Fact: There exists a bowling alley that is closed to the public.  (It only has one exit, in violation of firecodes).  It was constructed in 1914 for $850. Fun Fact 2:  Frick and his wife were scheduled to be on the Titantic, however they cancelled their travel plans when she twisted her ankle prior to the trip commencing. Fun Fact 3:  Saturdays are pay what you'd like.   ", neighborhood_id: upper_east_side.id)
neue_gallery = Place.create(name: "Neue Gallery New York", address: "1048 5th Avenue and 86th Street", latitude: 40.7813, longitude: -73.9603, description: "The Neue Gallery is a museum for early twentieth-century German and Austrian art.  The building was completed in 2001 and is an example of 'Beaux Arts Architecture'  Gustav Klimt's 'The Portrait of Adele Bloch Blauer' is on display here.  Fun Fact:  The adjoining cafe, The Cafe Sabarsky imports many of its pastries from Austria", neighborhood_id: upper_east_side.id)
waldorf = Place.create(name: "Waldorf Astoria", address: "301 Park Avenue at 50th Street", latitude: 40.7565, longitude: -73.97413, description: "The Waldorf Astoria is a luxury hotel as well as a historic landmark.  The building is one of the oldest examples of Art Deco Architecture in the World. It is currently owned and operated by the Hilton Family. Fun Fact 1:  While there are 1,416 guest rooms, no two rooms are exactly alike.  Fun Fact 2: The Waldorf Astoria was the first Hotel in the world to offer room service for its guests. Fun Fact 3:  Every president since Herbert Hoover has stayed in the presidential suite.  It is custom for each to leave a gift in the room.  (JFK left a rocking chair)", neighborhood_id: upper_east_side.id)
breakfast_tiffanys = Place.create(name: "Apartment from Breakfast at Tiffany's", address: "169 East 71st Street", latitude: 40.76964, longitude: -73.961886, description: "The apartment was used for the external shots from the 1961 Audrey Hepburn file.  It was previously owned by Peter E. Bacanovic, who was infamously involved in the Martha Stewart Insider Trading Case.  It was sold in 2012 for $5.89M  Fun Fact: Even though the film was nominated for 5 Academy Awards, Truman Capote was very vocal about his disdain for the film.  One of his complaints was that  the role of Holly Golightly was miscast.  Capote envisioned it going to Marilyn Monroe. ", neighborhood_id: upper_east_side.id)

